[project]
name = "langchain-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "langchain[google-genai,openai]>=1.0.3",
    "langchain-core>=1.0.3",
]
